project_id = "hulbzdhqiuczvqbnoivv"

[functions.sync-ctir-advisories]
verify_jwt = false

[functions.ar-audit]
verify_jwt = true

[functions.sync-nvd-vulnerabilities]
verify_jwt = false

[functions.notify-sync-failure]
verify_jwt = false

[functions.create-itsm-ticket]
verify_jwt = false
